import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { StrictMode } from 'react';
import { BrowserRouter, Link, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import './styles.css';

type Run = { id: string; status: string; progress: number; workflowCode: string; createdAt: string };
const queryClient = new QueryClient();
const api = async (path: string, options?: RequestInit) => (await fetch(path, options)).json();

function Layout({ children }: { children: React.ReactNode }) { return <div className="app-shell"><aside><strong>TestGen Agent</strong><nav><Link to="/dashboard">工作台</Link><Link to="/projects">项目管理</Link><Link to="/workflow-runs">Agent 任务</Link><Link className="disabled" to="/requirements">需求管理（建设中）</Link><Link className="disabled" to="/cases">用例管理（建设中）</Link><Link className="disabled" to="/knowledge">RAG 知识库（建设中）</Link></nav></aside><main><header><span>当前组织：默认组织</span><span>平台管理员　⌄</span></header>{children}</main></div>; }
function Dashboard() { const [runs, setRuns] = useState<Run[]>([]); const createRun = async () => { const result = await api('/api/v1/workflow-runs', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ organizationId:'demo-org', projectId:'demo-project', idempotencyKey:`demo-${Date.now()}`, input:{title:'演示任务',content:'验证 Agent 工作流链路'} }) }); if(result.data) setRuns((items)=>[result.data,...items]); }; return <section><p className="eyebrow">AGENT PLATFORM</p><h1>工作台</h1><p className="muted">React + NestJS + LangGraph.js 平台骨架已就绪。</p><div className="toolbar"><button onClick={createRun}>创建演示 Agent 任务</button><Link className="button-link" to="/workflow-runs">查看全部任务</Link></div><div className="cards"><article><b>项目</b><strong>0</strong><span>当前组织项目</span></article><article><b>最近运行</b><strong>{runs.length}</strong><span>Workflow Run</span></article><article><b>系统状态</b><strong className="ok">正常</strong><span>API / Worker</span></article></div></section>; }
function Projects() { return <section><p className="eyebrow">PROJECTS</p><h1>项目管理</h1><div className="panel"><p className="muted">项目 API 已提供基础列表、详情和创建接口。</p><button>创建项目</button></div></section>; }
function WorkflowRuns() { const [runs, setRuns] = useState<Run[]>([]); useEffect(()=>{ api('/api/v1/workflow-runs').then((result)=>setRuns(result.data ?? [])); },[]); return <section><p className="eyebrow">WORKFLOW RUNS</p><h1>Agent 任务</h1><div className="panel">{runs.length === 0 ? <p className="muted">暂无运行记录，可从工作台创建演示任务。</p> : runs.map((run)=><Link className="run" to={`/workflow-runs/${run.id}`} key={run.id}><span>{run.workflowCode}</span><b>{run.status}</b><small>{run.id}</small></Link>)}</div></section>; }
function RunDetail() { const { id } = useParams(); const [run, setRun] = useState<Run|null>(null); useEffect(()=>{if(id) api(`/api/v1/workflow-runs/${id}`).then((result)=>setRun(result.data));},[id]); return <section><p className="eyebrow">RUN DETAIL</p><h1>运行详情</h1><div className="panel">{run ? <><div className="run"><span>{run.workflowCode}</span><b>{run.status}</b><small>{run.id}</small></div><p className="muted">进度：{run.progress}%</p><p>事件流接口：<code>/api/v1/workflow-runs/{id}/stream</code></p></> : <p className="muted">加载中...</p>}</div></section>; }
function App() { return <BrowserRouter><Layout><Routes><Route path="/" element={<Dashboard/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/projects" element={<Projects/>}/><Route path="/workflow-runs" element={<WorkflowRuns/>}/><Route path="/workflow-runs/:id" element={<RunDetail/>}/><Route path="*" element={<Dashboard/>}/></Routes></Layout></BrowserRouter>; }
createRoot(document.getElementById('root')!).render(<StrictMode><QueryClientProvider client={queryClient}><App/></QueryClientProvider></StrictMode>);
